### PR TITLE
exposed imageView so that i can retrieve CGPoints using [gesture locationInView:mapView.imageView]

### PR DESCRIPTION
**Pull request by multinerd**
i was unable to accurately drop annotations when scale != 1. I’ve exposed the imageView so that when using gestures, you can get a more accurate CGPoint using something like [gesture locationInView:mapView.imageView]

### CODE REVIEW

**Comment by dblock** [comment]
I am not against this, but you do need to fix the build and update CHANGELOG, please.

**Comment by multinerd** [comment]
as much as id love to, when downloading from your repo directly i run into build errors myself. i have to change so much just to get it to work on my device. also, ive never had to deal with this builds before so i wouldnt know where to begin. all i did in the code was take out 

`@property (nonatomic, strong) UIImageView *imageView;` from NAMapView.m and placed it into NAMapView.h.

feel free to recreate the changes because as it stands i wouldnt know where to begin to get the build to pass

**Comment by multinerd** [comment]
i added a push to fix issue #45. when i get home after work, i'll tinker with travis CL and see what i can do about pushing a passing build.

**Comment by dblock** [comment]
I am not sure what's up with the build, but it *did* pass at some point on master in current state. I obviously don't want to merge something that's not passing CI. Appreciate your help.

**Comment by multinerd** [comment]
well if anyone else wants to make the PR im fine with that, the code should be visable

**Pull request closed without merging**
