### PR TITLE
Revised pin style

### PR DESCRIPTION
**Pull request by neilang**
Switching to an original set of push pins graphics for NAPinAnnotation. The old ones were out of date anyway.

Tests have been updated too.

### CODE REVIEW

**Comment by dblock** [comment]
Check the build, it should succeed on Travis. Also update CHANGELOG.

**Comment by neilang** [comment]
@dblock I'm unsure what is causing the build to fail, do you have any ideas? Tests pass locally.

**Comment by tonyarnold** [comment]
It's CocoaPods. :tada: :frowning:

**Comment by tonyarnold** [comment]
Now the tests are failing because there are tests that are doing image-based comparisons of the output 😕 

I have… _feelings_… about how useful tests of this nature are in small demo projects (or any projects). **Personally, I'd pull them out** and move on to more important tasks.

**Comment by neilang** [comment]
Thanks @tonyarnold. I think you're right and unfortunately I do not know enough about how the test setup works to fix this myself right now. I'll temporarily remove them for now.

**Comment by orta** [comment]
At a guess, it was probably because the tests are recorded on a 64 bit sim, and the tests are being ran on another device. But, YOLO.

**Comment by dblock** [comment]
FWIW there was a lot of effort put into making snapshot tests work in this project and they catch real bugs, otherwise there's literally no way to know whether map annotations work at all. I opened https://github.com/neilang/NAMapKit/issues/47.

**Pull request merged**
